<a href="https://colab.research.google.com/github/Keita062/soccer/blob/main/soccer(10_27).ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
data_1992=pd.read_csv("/content/1992.csv")
data_1993=pd.read_csv("/content/1993.csv")
data_1994=pd.read_csv("/content/1994.csv")
data_1995=pd.read_csv("/content/1995.csv")
data_1996=pd.read_csv("/content/1996.csv")
data_1997=pd.read_csv("/content/1997.csv")
data_1998=pd.read_csv("/content/1998.csv")
data_1999=pd.read_csv("/content/1999.csv")
data_2000=pd.read_csv("/content/2000.csv")
data_2001=pd.read_csv("/content/2001.csv")
data_2002=pd.read_csv("/content/2002.csv")
data_2003=pd.read_csv("/content/2003.csv")
data_2004=pd.read_csv("/content/2004.csv")
data_2005=pd.read_csv("/content/2005.csv")
data_2006=pd.read_csv("/content/2006.csv")
data_2007=pd.read_csv("/content/2007.csv")
data_2008=pd.read_csv("/content/2008.csv")
data_2009=pd.read_csv("/content/2009.csv")
data_2010=pd.read_csv("/content/2010.csv")
data_2011=pd.read_csv("/content/2011.csv")
data_2012=pd.read_csv("/content/2012.csv")
data_2013=pd.read_csv("/content/2013.csv")
data_2014=pd.read_csv("/content/2014.csv")
data_2015=pd.read_csv("/content/2015.csv")
data_2017=pd.read_csv("/content/2017.csv")
data_2018=pd.read_csv("/content/2018.csv")
data_2019=pd.read_csv("/content/2019.csv")
data_2020=pd.read_csv("/content/2020.csv")

In [3]:
# 読み込むCSVファイルのパスをリスト化
file_paths = [
    "/content/1992.csv", "/content/1993.csv", "/content/1994.csv", "/content/1995.csv",
    "/content/1996.csv", "/content/1997.csv", "/content/1998.csv", "/content/1999.csv",
    "/content/2000.csv", "/content/2001.csv", "/content/2002.csv", "/content/2003.csv",
    "/content/2004.csv", "/content/2005.csv", "/content/2006.csv", "/content/2007.csv",
    "/content/2008.csv", "/content/2009.csv", "/content/2010.csv", "/content/2011.csv",
    "/content/2012.csv", "/content/2013.csv", "/content/2014.csv", "/content/2015.csv",
    "/content/2017.csv", "/content/2018.csv", "/content/2019.csv", "/content/2020.csv"
]

# 各CSVファイルをDataFrameとして読み込み、リストに格納
data_frames = [pd.read_csv(file) for file in file_paths]

# すべてのDataFrameを縦方向に結合
total_premia_data  = pd.concat(data_frames, ignore_index=True)

# データ確認
total_premia_data

       Round             Date             Team 1   FT               Team 2
0          1  Sat Aug 15 1992         Arsenal FC  2-4      Norwich City FC
1          1  Sat Aug 15 1992    Leeds United FC  2-1         Wimbledon FC
2          1  Sat Aug 15 1992   Coventry City FC  2-1     Middlesbrough FC
3          1  Sat Aug 15 1992    Ipswich Town FC  1-1       Aston Villa FC
4          1  Sat Aug 15 1992  Crystal Palace FC  3-3  Blackburn Rovers FC
...      ...              ...                ...  ...                  ...
10881     38  Sun May 23 2021           West Ham  3–0          Southampton
10882     38  Sun May 23 2021       Leeds United  3–1            West Brom
10883     38  Sun May 23 2021            Arsenal  2–0             Brighton
10884     38  Sun May 23 2021          Liverpool  2–0       Crystal Palace
10885     38  Sun May 23 2021             Fulham  0–2        Newcastle Utd

[10886 rows x 5 columns]

In [4]:
total_premia_data.columns

Index(['Round', 'Date', 'Team 1', 'FT', 'Team 2'], dtype='object')

In [5]:
# Date列を曜日, 月, 日, 年に分割 (例: 'Sat Oct 14 2020')
total_premia_data[['Weekday', 'Month', 'Day', 'Year']] = total_premia_data['Date'].str.split(' ', expand=True)

# Day列を整数型に変換
total_premia_data['Day'] = pd.to_numeric(total_premia_data['Day'], errors='coerce')

# FT列(スコア)を分割 (例: '2-4' → 'Team1_Score' と 'Team2_Score')
total_premia_data[['Team1_Score', 'Team2_Score']] = total_premia_data['FT'].str.split('-', expand=True)

# スコア列を整数型に変換
total_premia_data['Team1_Score'] = pd.to_numeric(total_premia_data['Team1_Score'], errors='coerce')
total_premia_data['Team2_Score'] = pd.to_numeric(total_premia_data['Team2_Score'], errors='coerce')

# データ確認
total_premia_data.head()

,Round,Date,Team 1,FT,Team 2,Weekday,Month,Day,Year,Team1_Score,Team2_Score
0,1,Sat Aug 15 1992,Arsenal FC,2-4,Norwich City FC,Sat,Aug,15,1992,2.0,4.0
1,1,Sat Aug 15 1992,Leeds United FC,2-1,Wimbledon FC,Sat,Aug,15,1992,2.0,1.0
2,1,Sat Aug 15 1992,Coventry City FC,2-1,Middlesbrough FC,Sat,Aug,15,1992,2.0,1.0
3,1,Sat Aug 15 1992,Ipswich Town FC,1-1,Aston Villa FC,Sat,Aug,15,1992,1.0,1.0
4,1,Sat Aug 15 1992,Crystal Palace FC,3-3,Blackburn Rovers FC,Sat,Aug,15,1992,3.0,3.0

In [6]:
# 元のチーム名の配列
teams = np.array([
    'Manchester United FC', 'Arsenal FC', 'Chelsea FC', 'Liverpool FC',
    'Tottenham Hotspur FC', 'Everton FC', 'Manchester City FC',
    'Newcastle United FC', 'Aston Villa FC', 'West Ham United FC',
    'Blackburn Rovers FC', 'Southampton FC', 'Leeds United FC',
    'Middlesbrough FC', 'Leicester City FC', 'Fulham FC',
    'Sunderland AFC', 'Bolton Wanderers FC', 'Crystal Palace FC',
    'West Bromwich Albion FC', 'Stoke City FC', 'Coventry City FC',
    'Sheffield Wednesday FC', 'Wimbledon FC', 'Norwich City FC',
    'Charlton Athletic FC', 'Wigan Athletic FC',
    'Queens Park Rangers FC', 'Portsmouth FC', 'Birmingham City FC',
    'Derby County FC', 'Swansea City FC', 'Wolverhampton Wanderers FC',
    'Nottingham Forest FC', 'Ipswich Town FC', 'Watford FC',
    'Burnley FC', 'Sheffield United FC', 'AFC Bournemouth',
    'Hull City AFC', 'Reading FC', 'Brighton & Hove Albion FC',
    'Oldham Athletic AFC', 'Cardiff City FC', 'Bradford City AFC',
    'Huddersfield Town AFC', 'Blackpool FC', 'Tottenham', 'West Brom',
    'West Ham', 'Southampton', 'Liverpool', 'Sheffield Utd',
    'Newcastle Utd', 'Aston Villa', 'Brighton', 'Burnley', 'Chelsea',
    'Crystal Palace', 'Everton', 'Fulham', 'Leeds United',
    'Leicester City', 'Arsenal', 'Manchester City', 'Manchester Utd',
    'Wolves', 'Barnsley FC', 'Swindon Town FC'
])

# チーム名の標準化を行う辞書
team_name_mapping = {
    'Manchester United FC': 'Manchester United',
    'Manchester Utd': 'Manchester United',
    'Arsenal FC': 'Arsenal',
    'Arsenal': 'Arsenal',
    'Chelsea FC': 'Chelsea',
    'Chelsea': 'Chelsea',
    'Liverpool FC': 'Liverpool',
    'Liverpool': 'Liverpool',
    'Tottenham Hotspur FC': 'Tottenham Hotspur',
    'Tottenham': 'Tottenham Hotspur',
    'Everton FC': 'Everton',
    'Everton': 'Everton',
    'Manchester City FC': 'Manchester City',
    'Manchester City': 'Manchester City',
    'Newcastle United FC': 'Newcastle United',
    'Newcastle Utd': 'Newcastle United',
    'Aston Villa FC': 'Aston Villa',
    'Aston Villa': 'Aston Villa',
    'West Ham United FC': 'West Ham United',
    'West Ham': 'West Ham United',
    'Southampton FC': 'Southampton',
    'Southampton': 'Southampton',
    'Fulham FC': 'Fulham',
    'Fulham': 'Fulham',
    'Leeds United FC': 'Leeds United',
    'Leeds United': 'Leeds United',
    'Leicester City FC': 'Leicester City',
    'Leicester City': 'Leicester City',
    'Brighton & Hove Albion FC': 'Brighton',
    'Brighton': 'Brighton',
    'Burnley FC': 'Burnley',
    'Burnley': 'Burnley',
    'Wolverhampton Wanderers FC': 'Wolves',
    'Wolves': 'Wolves',
    # 追加のチーム名のマッピングをここに追加できます
}

# チーム名を標準化する
standardized_teams = np.array([team_name_mapping.get(team, team) for team in teams])

# 結果を表示
unique_teams = np.unique(standardized_teams)
unique_teams

array(['AFC Bournemouth', 'Arsenal', 'Aston Villa', 'Barnsley FC',
       'Birmingham City FC', 'Blackburn Rovers FC', 'Blackpool FC',
       'Bolton Wanderers FC', 'Bradford City AFC', 'Brighton', 'Burnley',
       'Cardiff City FC', 'Charlton Athletic FC', 'Chelsea',
       'Coventry City FC', 'Crystal Palace', 'Crystal Palace FC',
       'Derby County FC', 'Everton', 'Fulham', 'Huddersfield Town AFC',
       'Hull City AFC', 'Ipswich Town FC', 'Leeds United',
       'Leicester City', 'Liverpool', 'Manchester City',
       'Manchester United', 'Middlesbrough FC', 'Newcastle United',
       'Norwich City FC', 'Nottingham Forest FC', 'Oldham Athletic AFC',
       'Portsmouth FC', 'Queens Park Rangers FC', 'Reading FC',
       'Sheffield United FC', 'Sheffield Utd', 'Sheffield Wednesday FC',
       'Southampton', 'Stoke City FC', 'Sunderland AFC',
       'Swansea City FC', 'Swindon Town FC', 'Tottenham Hotspur',
       'Watford FC', 'West Brom', 'West Bromwich Albion FC',
       'West Ham United', 'Wigan Athletic FC', 'Wimbledon FC', 'Wolves'],
      dtype='<U23')

In [7]:
total_premia_data['Team 1'] = total_premia_data['Team 1'].map(team_name_mapping).fillna(total_premia_data['Team 1'])
total_premia_data['Team 2'] = total_premia_data['Team 2'].map(team_name_mapping).fillna(total_premia_data['Team 2'])

In [8]:
import pandas as pd

# 1. チームごとの勝敗・得失点などのデータを初期化する
teams_stats = []

# 2. 各試合の結果をもとに、勝敗や得点を集計
for _, row in total_premia_data.iterrows():
    team1, team2 = row['Team 1'], row['Team 2']
    score1, score2 = row['Team1_Score'], row['Team2_Score']

    # 勝敗の判定
    if score1 > score2:
        result1, result2 = 'win', 'loss'
    elif score1 < score2:
        result1, result2 = 'loss', 'win'
    else:
        result1, result2 = 'draw', 'draw'

    # 各チームの試合結果をリストに格納
    teams_stats.extend([
        {'Team': team1, 'Result': result1, 'GoalsScored': score1, 'GoalsConceded': score2},
        {'Team': team2, 'Result': result2, 'GoalsScored': score2, 'GoalsConceded': score1}
    ])

# 3. DataFrameに変換
df_stats = pd.DataFrame(teams_stats)

# 4. 集計処理
summary = df_stats.groupby(['Team']).agg(
    Matches=('Result', 'count'),
    Wins=('Result', lambda x: (x == 'win').sum()),
    Draws=('Result', lambda x: (x == 'draw').sum()),
    Losses=('Result', lambda x: (x == 'loss').sum()),
    GoalsScored=('GoalsScored', 'sum'),
    GoalsConceded=('GoalsConceded', 'sum')
).reset_index()

# 5. 得失点差と勝点を計算
summary['GoalDifference'] = summary['GoalsScored'] - summary['GoalsConceded']
summary['Points'] = summary['Wins'] * 3 + summary['Draws']

# 6. データフレームを表示
summary

,Team,Matches,Wins,Draws,Losses,GoalsScored,GoalsConceded,GoalDifference,Points
0,AFC Bournemouth,152,44,33,75,186.0,263.0,-77.0,165
1,Arsenal,1076,556,306,214,1824.0,1017.0,807.0,1974
2,Aston Villa,1000,325,321,354,1158.0,1253.0,-95.0,1296
3,Barnsley FC,38,10,5,23,37.0,82.0,-45.0,35
4,Birmingham City FC,266,73,82,111,273.0,360.0,-87.0,301
5,Blackburn Rovers FC,696,262,184,250,927.0,907.0,20.0,970
6,Blackpool FC,38,10,9,19,55.0,78.0,-23.0,39
7,Bolton Wanderers FC,494,149,128,217,575.0,745.0,-170.0,575
8,Bradford City AFC,76,14,20,42,68.0,138.0,-70.0,62
9,Brighton,152,27,74,51,108.0,168.0,-60.0,155
10,Burnley,228,55,84,89,194.0,292.0,-98.0,249
11,Cardiff City FC,76,17,13,46,66.0,143.0,-77.0,64
12,Charlton Athletic FC,304,93,82,129,342.0,442.0,-100.0,361
13,Chelsea,1076,548,298,230,1754.0,1023.0,731.0,1942
14,Coventry City FC,354,99,112,143,387.0,490.0,-103.0,409
15,Crystal Palace,38,0,38,0,0.0,0.0,0.0,38
16,Crystal Palace FC,388,110,101,177,406.0,551.0,-145.0,431
17,Derby County FC,266,68,70,128,271.0,420.0,-149.0,274
18,Everton,1076,373,334,369,1339.0,1323.0,16.0,1453
19,Fulham,570,157,179,234,604.0,778.0,-174.0,650
20,Huddersfield Town AFC,76,12,17,47,50.0,134.0,-84.0,53
21,Hull City AFC,152,32,41,79,144.0,243.0,-99.0,137
22,Ipswich Town FC,202,57,53,92,219.0,312.0,-93.0,224
23,Leeds United,506,189,163,154,641.0,573.0,68.0,730
24,Leicester City,536,163,174,199,642.0,696.0,-54.0,663
25,Liverpool,1076,539,293,244,1781.0,1037.0,744.0,1910
26,Manchester City,886,394,228,264,1396.0,971.0,425.0,1410
27,Manchester United,1076,648,259,169,2001.0,936.0,1065.0,2203
28,Middlesbrough FC,536,160,156,220,621.0,741.0,-120.0,636
29,Newcastle United,996,357,283,356,1287.0,1293.0,-6.0,1354
30,Norwich City FC,354,94,98,162,391.0,585.0,-194.0,380
31,Nottingham Forest FC,198,60,59,79,229.0,287.0,-58.0,239
32,Oldham Athletic AFC,84,22,23,39,105.0,142.0,-37.0,89
33,Portsmouth FC,266,79,65,122,292.0,380.0,-88.0,302
34,Queens Park Rangers FC,278,81,65,132,339.0,431.0,-92.0,308
35,Reading FC,114,32,23,59,136.0,186.0,-50.0,119
36,Sheffield United FC,160,46,48,66,167.0,207.0,-40.0,186
37,Sheffield Utd,38,0,38,0,0.0,0.0,0.0,38
38,Sheffield Wednesday FC,316,101,89,126,409.0,453.0,-44.0,392
39,Southampton,810,241,249,320,947.0,1099.0,-152.0,972
40,Stoke City FC,342,105,98,139,357.0,469.0,-112.0,413
41,Sunderland AFC,570,147,153,270,583.0,835.0,-252.0,594
42,Swansea City FC,228,70,61,97,261.0,313.0,-52.0,271
43,Swindon Town FC,42,5,15,22,47.0,100.0,-53.0,30
44,Tottenham Hotspur,1076,436,298,342,1522.0,1327.0,195.0,1606
45,Watford FC,228,56,54,118,236.0,373.0,-137.0,222
46,West Brom,38,0,38,0,0.0,0.0,0.0,38
47,West Bromwich Albion FC,418,100,119,199,432.0,645.0,-213.0,419
48,West Ham United,920,288,266,366,1066.0,1267.0,-201.0,1130
49,Wigan Athletic FC,304,85,76,143,316.0,482.0,-166.0,331
50,Wimbledon FC,316,99,94,123,384.0,472.0,-88.0,391
51,Wolves,266,63,101,102,254.0,367.0,-113.0,290

In [9]:
summary_sort=summary.sort_values(by='Matches',ascending=False)
summary_sort

,Team,Matches,Wins,Draws,Losses,GoalsScored,GoalsConceded,GoalDifference,Points
27,Manchester United,1076,648,259,169,2001.0,936.0,1065.0,2203
1,Arsenal,1076,556,306,214,1824.0,1017.0,807.0,1974
25,Liverpool,1076,539,293,244,1781.0,1037.0,744.0,1910
44,Tottenham Hotspur,1076,436,298,342,1522.0,1327.0,195.0,1606
18,Everton,1076,373,334,369,1339.0,1323.0,16.0,1453
13,Chelsea,1076,548,298,230,1754.0,1023.0,731.0,1942
2,Aston Villa,1000,325,321,354,1158.0,1253.0,-95.0,1296
29,Newcastle United,996,357,283,356,1287.0,1293.0,-6.0,1354
48,West Ham United,920,288,266,366,1066.0,1267.0,-201.0,1130
26,Manchester City,886,394,228,264,1396.0,971.0,425.0,1410
39,Southampton,810,241,249,320,947.0,1099.0,-152.0,972
5,Blackburn Rovers FC,696,262,184,250,927.0,907.0,20.0,970
41,Sunderland AFC,570,147,153,270,583.0,835.0,-252.0,594
19,Fulham,570,157,179,234,604.0,778.0,-174.0,650
24,Leicester City,536,163,174,199,642.0,696.0,-54.0,663
28,Middlesbrough FC,536,160,156,220,621.0,741.0,-120.0,636
23,Leeds United,506,189,163,154,641.0,573.0,68.0,730
7,Bolton Wanderers FC,494,149,128,217,575.0,745.0,-170.0,575
47,West Bromwich Albion FC,418,100,119,199,432.0,645.0,-213.0,419
16,Crystal Palace FC,388,110,101,177,406.0,551.0,-145.0,431
30,Norwich City FC,354,94,98,162,391.0,585.0,-194.0,380
14,Coventry City FC,354,99,112,143,387.0,490.0,-103.0,409
40,Stoke City FC,342,105,98,139,357.0,469.0,-112.0,413
38,Sheffield Wednesday FC,316,101,89,126,409.0,453.0,-44.0,392
50,Wimbledon FC,316,99,94,123,384.0,472.0,-88.0,391
12,Charlton Athletic FC,304,93,82,129,342.0,442.0,-100.0,361
49,Wigan Athletic FC,304,85,76,143,316.0,482.0,-166.0,331
34,Queens Park Rangers FC,278,81,65,132,339.0,431.0,-92.0,308
33,Portsmouth FC,266,79,65,122,292.0,380.0,-88.0,302
51,Wolves,266,63,101,102,254.0,367.0,-113.0,290
17,Derby County FC,266,68,70,128,271.0,420.0,-149.0,274
4,Birmingham City FC,266,73,82,111,273.0,360.0,-87.0,301
10,Burnley,228,55,84,89,194.0,292.0,-98.0,249
45,Watford FC,228,56,54,118,236.0,373.0,-137.0,222
42,Swansea City FC,228,70,61,97,261.0,313.0,-52.0,271
22,Ipswich Town FC,202,57,53,92,219.0,312.0,-93.0,224
31,Nottingham Forest FC,198,60,59,79,229.0,287.0,-58.0,239
36,Sheffield United FC,160,46,48,66,167.0,207.0,-40.0,186
9,Brighton,152,27,74,51,108.0,168.0,-60.0,155
21,Hull City AFC,152,32,41,79,144.0,243.0,-99.0,137
0,AFC Bournemouth,152,44,33,75,186.0,263.0,-77.0,165
35,Reading FC,114,32,23,59,136.0,186.0,-50.0,119
32,Oldham Athletic AFC,84,22,23,39,105.0,142.0,-37.0,89
11,Cardiff City FC,76,17,13,46,66.0,143.0,-77.0,64
20,Huddersfield Town AFC,76,12,17,47,50.0,134.0,-84.0,53
8,Bradford City AFC,76,14,20,42,68.0,138.0,-70.0,62
43,Swindon Town FC,42,5,15,22,47.0,100.0,-53.0,30
37,Sheffield Utd,38,0,38,0,0.0,0.0,0.0,38
15,Crystal Palace,38,0,38,0,0.0,0.0,0.0,38
46,West Brom,38,0,38,0,0.0,0.0,0.0,38
6,Blackpool FC,38,10,9,19,55.0,78.0,-23.0,39
3,Barnsley FC,38,10,5,23,37.0,82.0,-45.0,35

In [10]:
summary['Team'].unique()

array(['AFC Bournemouth', 'Arsenal', 'Aston Villa', 'Barnsley FC',
       'Birmingham City FC', 'Blackburn Rovers FC', 'Blackpool FC',
       'Bolton Wanderers FC', 'Bradford City AFC', 'Brighton', 'Burnley',
       'Cardiff City FC', 'Charlton Athletic FC', 'Chelsea',
       'Coventry City FC', 'Crystal Palace', 'Crystal Palace FC',
       'Derby County FC', 'Everton', 'Fulham', 'Huddersfield Town AFC',
       'Hull City AFC', 'Ipswich Town FC', 'Leeds United',
       'Leicester City', 'Liverpool', 'Manchester City',
       'Manchester United', 'Middlesbrough FC', 'Newcastle United',
       'Norwich City FC', 'Nottingham Forest FC', 'Oldham Athletic AFC',
       'Portsmouth FC', 'Queens Park Rangers FC', 'Reading FC',
       'Sheffield United FC', 'Sheffield Utd', 'Sheffield Wednesday FC',
       'Southampton', 'Stoke City FC', 'Sunderland AFC',
       'Swansea City FC', 'Swindon Town FC', 'Tottenham Hotspur',
       'Watford FC', 'West Brom', 'West Bromwich Albion FC',
       'West Ham United', 'Wigan Athletic FC', 'Wimbledon FC', 'Wolves'],
      dtype=object)

In [11]:
match_sorted_data = summary.groupby('Matches').apply(lambda x: x.sort_values('Points', ascending=True)).reset_index(drop=True)

# 結果を表示
match_sorted_data

<ipython-input-11-152d9587408e>:1: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  match_sorted_data = summary.groupby('Matches').apply(lambda x: x.sort_values('Points', ascending=True)).reset_index(drop=True)

,Team,Matches,Wins,Draws,Losses,GoalsScored,GoalsConceded,GoalDifference,Points
0,Barnsley FC,38,10,5,23,37.0,82.0,-45.0,35
1,Crystal Palace,38,0,38,0,0.0,0.0,0.0,38
2,Sheffield Utd,38,0,38,0,0.0,0.0,0.0,38
3,West Brom,38,0,38,0,0.0,0.0,0.0,38
4,Blackpool FC,38,10,9,19,55.0,78.0,-23.0,39
5,Swindon Town FC,42,5,15,22,47.0,100.0,-53.0,30
6,Huddersfield Town AFC,76,12,17,47,50.0,134.0,-84.0,53
7,Bradford City AFC,76,14,20,42,68.0,138.0,-70.0,62
8,Cardiff City FC,76,17,13,46,66.0,143.0,-77.0,64
9,Oldham Athletic AFC,84,22,23,39,105.0,142.0,-37.0,89
10,Reading FC,114,32,23,59,136.0,186.0,-50.0,119
11,Hull City AFC,152,32,41,79,144.0,243.0,-99.0,137
12,Brighton,152,27,74,51,108.0,168.0,-60.0,155
13,AFC Bournemouth,152,44,33,75,186.0,263.0,-77.0,165
14,Sheffield United FC,160,46,48,66,167.0,207.0,-40.0,186
15,Nottingham Forest FC,198,60,59,79,229.0,287.0,-58.0,239
16,Ipswich Town FC,202,57,53,92,219.0,312.0,-93.0,224
17,Watford FC,228,56,54,118,236.0,373.0,-137.0,222
18,Burnley,228,55,84,89,194.0,292.0,-98.0,249
19,Swansea City FC,228,70,61,97,261.0,313.0,-52.0,271
20,Derby County FC,266,68,70,128,271.0,420.0,-149.0,274
21,Wolves,266,63,101,102,254.0,367.0,-113.0,290
22,Birmingham City FC,266,73,82,111,273.0,360.0,-87.0,301
23,Portsmouth FC,266,79,65,122,292.0,380.0,-88.0,302
24,Queens Park Rangers FC,278,81,65,132,339.0,431.0,-92.0,308
25,Wigan Athletic FC,304,85,76,143,316.0,482.0,-166.0,331
26,Charlton Athletic FC,304,93,82,129,342.0,442.0,-100.0,361
27,Wimbledon FC,316,99,94,123,384.0,472.0,-88.0,391
28,Sheffield Wednesday FC,316,101,89,126,409.0,453.0,-44.0,392
29,Stoke City FC,342,105,98,139,357.0,469.0,-112.0,413
30,Norwich City FC,354,94,98,162,391.0,585.0,-194.0,380
31,Coventry City FC,354,99,112,143,387.0,490.0,-103.0,409
32,Crystal Palace FC,388,110,101,177,406.0,551.0,-145.0,431
33,West Bromwich Albion FC,418,100,119,199,432.0,645.0,-213.0,419
34,Bolton Wanderers FC,494,149,128,217,575.0,745.0,-170.0,575
35,Leeds United,506,189,163,154,641.0,573.0,68.0,730
36,Middlesbrough FC,536,160,156,220,621.0,741.0,-120.0,636
37,Leicester City,536,163,174,199,642.0,696.0,-54.0,663
38,Sunderland AFC,570,147,153,270,583.0,835.0,-252.0,594
39,Fulham,570,157,179,234,604.0,778.0,-174.0,650
40,Blackburn Rovers FC,696,262,184,250,927.0,907.0,20.0,970
41,Southampton,810,241,249,320,947.0,1099.0,-152.0,972
42,Manchester City,886,394,228,264,1396.0,971.0,425.0,1410
43,West Ham United,920,288,266,366,1066.0,1267.0,-201.0,1130
44,Newcastle United,996,357,283,356,1287.0,1293.0,-6.0,1354
45,Aston Villa,1000,325,321,354,1158.0,1253.0,-95.0,1296
46,Everton,1076,373,334,369,1339.0,1323.0,16.0,1453
47,Tottenham Hotspur,1076,436,298,342,1522.0,1327.0,195.0,1606
48,Liverpool,1076,539,293,244,1781.0,1037.0,744.0,1910
49,Chelsea,1076,548,298,230,1754.0,1023.0,731.0,1942
50,Arsenal,1076,556,306,214,1824.0,1017.0,807.0,1974
51,Manchester United,1076,648,259,169,2001.0,936.0,1065.0,2203

In [12]:
match_sorted_data = summary.sort_values(by=['Matches', 'Points'], ascending=[False, False])
match_sorted_data

,Team,Matches,Wins,Draws,Losses,GoalsScored,GoalsConceded,GoalDifference,Points
27,Manchester United,1076,648,259,169,2001.0,936.0,1065.0,2203
1,Arsenal,1076,556,306,214,1824.0,1017.0,807.0,1974
13,Chelsea,1076,548,298,230,1754.0,1023.0,731.0,1942
25,Liverpool,1076,539,293,244,1781.0,1037.0,744.0,1910
44,Tottenham Hotspur,1076,436,298,342,1522.0,1327.0,195.0,1606
18,Everton,1076,373,334,369,1339.0,1323.0,16.0,1453
2,Aston Villa,1000,325,321,354,1158.0,1253.0,-95.0,1296
29,Newcastle United,996,357,283,356,1287.0,1293.0,-6.0,1354
48,West Ham United,920,288,266,366,1066.0,1267.0,-201.0,1130
26,Manchester City,886,394,228,264,1396.0,971.0,425.0,1410
39,Southampton,810,241,249,320,947.0,1099.0,-152.0,972
5,Blackburn Rovers FC,696,262,184,250,927.0,907.0,20.0,970
19,Fulham,570,157,179,234,604.0,778.0,-174.0,650
41,Sunderland AFC,570,147,153,270,583.0,835.0,-252.0,594
24,Leicester City,536,163,174,199,642.0,696.0,-54.0,663
28,Middlesbrough FC,536,160,156,220,621.0,741.0,-120.0,636
23,Leeds United,506,189,163,154,641.0,573.0,68.0,730
7,Bolton Wanderers FC,494,149,128,217,575.0,745.0,-170.0,575
47,West Bromwich Albion FC,418,100,119,199,432.0,645.0,-213.0,419
16,Crystal Palace FC,388,110,101,177,406.0,551.0,-145.0,431
14,Coventry City FC,354,99,112,143,387.0,490.0,-103.0,409
30,Norwich City FC,354,94,98,162,391.0,585.0,-194.0,380
40,Stoke City FC,342,105,98,139,357.0,469.0,-112.0,413
38,Sheffield Wednesday FC,316,101,89,126,409.0,453.0,-44.0,392
50,Wimbledon FC,316,99,94,123,384.0,472.0,-88.0,391
12,Charlton Athletic FC,304,93,82,129,342.0,442.0,-100.0,361
49,Wigan Athletic FC,304,85,76,143,316.0,482.0,-166.0,331
34,Queens Park Rangers FC,278,81,65,132,339.0,431.0,-92.0,308
33,Portsmouth FC,266,79,65,122,292.0,380.0,-88.0,302
4,Birmingham City FC,266,73,82,111,273.0,360.0,-87.0,301
51,Wolves,266,63,101,102,254.0,367.0,-113.0,290
17,Derby County FC,266,68,70,128,271.0,420.0,-149.0,274
42,Swansea City FC,228,70,61,97,261.0,313.0,-52.0,271
10,Burnley,228,55,84,89,194.0,292.0,-98.0,249
45,Watford FC,228,56,54,118,236.0,373.0,-137.0,222
22,Ipswich Town FC,202,57,53,92,219.0,312.0,-93.0,224
31,Nottingham Forest FC,198,60,59,79,229.0,287.0,-58.0,239
36,Sheffield United FC,160,46,48,66,167.0,207.0,-40.0,186
0,AFC Bournemouth,152,44,33,75,186.0,263.0,-77.0,165
9,Brighton,152,27,74,51,108.0,168.0,-60.0,155
21,Hull City AFC,152,32,41,79,144.0,243.0,-99.0,137
35,Reading FC,114,32,23,59,136.0,186.0,-50.0,119
32,Oldham Athletic AFC,84,22,23,39,105.0,142.0,-37.0,89
11,Cardiff City FC,76,17,13,46,66.0,143.0,-77.0,64
8,Bradford City AFC,76,14,20,42,68.0,138.0,-70.0,62
20,Huddersfield Town AFC,76,12,17,47,50.0,134.0,-84.0,53
43,Swindon Town FC,42,5,15,22,47.0,100.0,-53.0,30
6,Blackpool FC,38,10,9,19,55.0,78.0,-23.0,39
15,Crystal Palace,38,0,38,0,0.0,0.0,0.0,38
37,Sheffield Utd,38,0,38,0,0.0,0.0,0.0,38
46,West Brom,38,0,38,0,0.0,0.0,0.0,38
3,Barnsley FC,38,10,5,23,37.0,82.0,-45.0,35

In [13]:
summary['Team'].unique()

array(['AFC Bournemouth', 'Arsenal', 'Aston Villa', 'Barnsley FC',
       'Birmingham City FC', 'Blackburn Rovers FC', 'Blackpool FC',
       'Bolton Wanderers FC', 'Bradford City AFC', 'Brighton', 'Burnley',
       'Cardiff City FC', 'Charlton Athletic FC', 'Chelsea',
       'Coventry City FC', 'Crystal Palace', 'Crystal Palace FC',
       'Derby County FC', 'Everton', 'Fulham', 'Huddersfield Town AFC',
       'Hull City AFC', 'Ipswich Town FC', 'Leeds United',
       'Leicester City', 'Liverpool', 'Manchester City',
       'Manchester United', 'Middlesbrough FC', 'Newcastle United',
       'Norwich City FC', 'Nottingham Forest FC', 'Oldham Athletic AFC',
       'Portsmouth FC', 'Queens Park Rangers FC', 'Reading FC',
       'Sheffield United FC', 'Sheffield Utd', 'Sheffield Wednesday FC',
       'Southampton', 'Stoke City FC', 'Sunderland AFC',
       'Swansea City FC', 'Swindon Town FC', 'Tottenham Hotspur',
       'Watford FC', 'West Brom', 'West Bromwich Albion FC',
       'West Ham United', 'Wigan Athletic FC', 'Wimbledon FC', 'Wolves'],
      dtype=object)

In [25]:
total_premia_data.columns

Index(['Round', 'Date', 'Team 1', 'FT', 'Team 2', 'Weekday', 'Month', 'Day',
       'Year', 'Team1_Score', 'Team2_Score'],
      dtype='object')

In [21]:
# ビッグ6クラブのリスト
big6_teams  = ["Manchester United", "Liverpool", "Chelsea", "Arsenal", "Manchester City", "Tottenham Hotspur"]
big6_data = summary[summary['Team'].isin(big6_teams)]
big6_data

,Team,Matches,Wins,Draws,Losses,GoalsScored,GoalsConceded,GoalDifference,Points
1,Arsenal,1076,556,306,214,1824.0,1017.0,807.0,1974
13,Chelsea,1076,548,298,230,1754.0,1023.0,731.0,1942
25,Liverpool,1076,539,293,244,1781.0,1037.0,744.0,1910
26,Manchester City,886,394,228,264,1396.0,971.0,425.0,1410
27,Manchester United,1076,648,259,169,2001.0,936.0,1065.0,2203
44,Tottenham Hotspur,1076,436,298,342,1522.0,1327.0,195.0,1606

In [28]:
# ビッグ6同士の試合を抽出
big6_matches = total_premia_data[
    (total_premia_data['Team 1'].isin(big6_teams)) &
    (total_premia_data['Team 2'].isin(big6_teams))
]

# 各チームの成績を集計するための辞書を初期化 (勝ち、負け、試合数、引き分け)
results = {team: {opponent: {'wins': 0, 'losses': 0, 'draws': 0, 'games': 0}
                  for opponent in big6_teams}
           for team in big6_teams}

# 勝利チームと引き分けの判定
for _, row in big6_matches.iterrows():
    team1, team2 = row['Team 1'], row['Team 2']
    score1, score2 = row['Team1_Score'], row['Team2_Score']

    # 対戦回数をカウント
    results[team1][team2]['games'] += 1
    results[team2][team1]['games'] += 1

    if score1 > score2:
        # team1が勝ち、team2が負け
        results[team1][team2]['wins'] += 1
        results[team2][team1]['losses'] += 1
    elif score2 > score1:
        # team2が勝ち、team1が負け
        results[team2][team1]['wins'] += 1
        results[team1][team2]['losses'] += 1
    else:
        # 引き分けの場合
        results[team1][team2]['draws'] += 1
        results[team2][team1]['draws'] += 1

# 勝ち、負け、引き分けの表を作成する関数
def create_league_table(results, stat):
    table = pd.DataFrame(index=big6_teams, columns=big6_teams)
    for team1 in big6_teams:
        for team2 in big6_teams:
            if team1 != team2:
                value = results[team1][team2][stat]
                games = results[team1][team2]['games']
                table.at[team1, team2] = f"{value} ({games})"
            else:
                table.at[team1, team2] = "-"
    return table

# 各成績表の作成
win_table = create_league_table(results, 'wins')
loss_table = create_league_table(results, 'losses')
draw_table = create_league_table(results, 'draws')

In [31]:
# 各リーグ戦表の表示
print("\n勝ち数リーグ表 (勝ち数(試合数)):")
win_table

勝ち数リーグ表 (勝ち数(試合数)):

,Manchester United,Liverpool,Chelsea,Arsenal,Manchester City,Tottenham Hotspur
Manchester United,-,28 (56),16 (56),24 (56),23 (46),34 (56)
Liverpool,15 (56),-,21 (56),19 (56),19 (46),26 (56)
Chelsea,17 (56),20 (56),-,18 (56),24 (46),29 (56)
Arsenal,14 (56),16 (56),19 (56),-,23 (46),20 (56)
Manchester City,14 (46),10 (46),13 (46),12 (46),-,15 (46)
Tottenham Hotspur,8 (56),14 (56),6 (56),12 (56),23 (46),-

In [32]:
print("\n負け数リーグ表 (負け数(試合数)):")
loss_table

負け数リーグ表 (負け数(試合数)):

,Manchester United,Liverpool,Chelsea,Arsenal,Manchester City,Tottenham Hotspur
Manchester United,-,15 (56),17 (56),14 (56),14 (46),8 (56)
Liverpool,28 (56),-,20 (56),16 (56),10 (46),14 (56)
Chelsea,16 (56),21 (56),-,19 (56),13 (46),6 (56)
Arsenal,24 (56),19 (56),18 (56),-,12 (46),12 (56)
Manchester City,23 (46),19 (46),24 (46),23 (46),-,23 (46)
Tottenham Hotspur,34 (56),26 (56),29 (56),20 (56),15 (46),-

In [33]:
print("\n引き分け数リーグ表 (引き分け数(試合数)):")
draw_table

引き分け数リーグ表 (引き分け数(試合数)):

,Manchester United,Liverpool,Chelsea,Arsenal,Manchester City,Tottenham Hotspur
Manchester United,-,13 (56),23 (56),18 (56),9 (46),14 (56)
Liverpool,13 (56),-,15 (56),21 (56),17 (46),16 (56)
Chelsea,23 (56),15 (56),-,19 (56),9 (46),21 (56)
Arsenal,18 (56),21 (56),19 (56),-,11 (46),24 (56)
Manchester City,9 (46),17 (46),9 (46),11 (46),-,8 (46)
Tottenham Hotspur,14 (56),16 (56),21 (56),24 (56),8 (46),-

In [34]:
import pandas as pd

# ビッグ6クラブのリスト
big6_teams = ["Manchester United", "Liverpool", "Chelsea",
              "Arsenal", "Manchester City", "Tottenham Hotspur"]

# ビッグ6同士の試合を抽出
big6_matches = total_premia_data[
    (total_premia_data['Team 1'].isin(big6_teams)) &
    (total_premia_data['Team 2'].isin(big6_teams))
]

# 各チームの成績を集計するための辞書を初期化
results = {team: {opponent: {'wins': 0, 'losses': 0, 'draws': 0, 'games': 0}
                  for opponent in big6_teams}
           for team in big6_teams}

# 勝利チーム、負けチーム、引き分けの判定
for _, row in big6_matches.iterrows():
    team1, team2 = row['Team 1'], row['Team 2']
    score1, score2 = row['Team1_Score'], row['Team2_Score']

    # 対戦回数をカウント
    results[team1][team2]['games'] += 1
    results[team2][team1]['games'] += 1

    if score1 > score2:
        # team1が勝ち、team2が負け
        results[team1][team2]['wins'] += 1
        results[team2][team1]['losses'] += 1
    elif score2 > score1:
        # team2が勝ち、team1が負け
        results[team2][team1]['wins'] += 1
        results[team1][team2]['losses'] += 1
    else:
        # 引き分けの場合
        results[team1][team2]['draws'] += 1
        results[team2][team1]['draws'] += 1

# 勝ち数 - 引き分け数 - 負け数 (試合数) 形式の表を作成する関数
def create_summary_table(results):
    table = pd.DataFrame(index=big6_teams, columns=big6_teams)
    for team1 in big6_teams:
        for team2 in big6_teams:
            if team1 != team2:
                wins = results[team1][team2]['wins']
                draws = results[team1][team2]['draws']
                losses = results[team1][team2]['losses']
                games = results[team1][team2]['games']
                table.at[team1, team2] = f"{wins}-{draws}-{losses} ({games})"
            else:
                table.at[team1, team2] = "-"
    return table

# 成績表を作成
summary_table = create_summary_table(results)

# 成績表の表示
print("\n勝ち数-引き分け数-負け数-(試合数)のリーグ戦表:")
summary_table

勝ち数-引き分け数-負け数-(試合数)のリーグ戦表:

,Manchester United,Liverpool,Chelsea,Arsenal,Manchester City,Tottenham Hotspur
Manchester United,-,28-13-15 (56),16-23-17 (56),24-18-14 (56),23-9-14 (46),34-14-8 (56)
Liverpool,15-13-28 (56),-,21-15-20 (56),19-21-16 (56),19-17-10 (46),26-16-14 (56)
Chelsea,17-23-16 (56),20-15-21 (56),-,18-19-19 (56),24-9-13 (46),29-21-6 (56)
Arsenal,14-18-24 (56),16-21-19 (56),19-19-18 (56),-,23-11-12 (46),20-24-12 (56)
Manchester City,14-9-23 (46),10-17-19 (46),13-9-24 (46),12-11-23 (46),-,15-8-23 (46)
Tottenham Hotspur,8-14-34 (56),14-16-26 (56),6-21-29 (56),12-24-20 (56),23-8-15 (46),-